version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: notes
      POSTGRES_PASSWORD: "hen3iNufkzl24MCoKGOUglnnp1E0wFLA"
    volumes:
      - notes_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "B3_PsZj5WFbCyWgPsiU6wIuQM6jB8OWo"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  notes_data:
